baseurl: ""
url: "https://therhyswyrill.github.io"

title: "The Playability Report"
page_title: "The Playability Report | Game Reviews, Benchmarks & Longplays"
description: "In-depth game reviews, emulation benchmarks, and Proton compatibility testing. Discover performance reports and curated gameplay longplays in one archive."
avatar: assets/img/avatar.png
favicon: assets/icon.ico

header_text: "Analyzing Performance, Reviewing the Experience, and Archiving the Journey"
header_feature_image: assets/img/header/hero.webp
header_feature_image_responsive: true
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> | The Playability Report

color_image: /assets/img/lineart.png
color_theme: dark

katex: false
mermaid: false
excerpt: false
post_navigation: false
cookie_consent: false

sass:
  style: compressed
  quiet_deps: true

plugins: 
  - jekyll-seo-tag

exclude:
  - ".idea"
  - ".jekyll-cache"
  - ".jekyll-metadata"
  - ".sass-cache"
  - "Gemfile"
  - "Gemfile.lock"
  - "type-on-strap.gemspec"
  - "vendor"
  - "node_modules"
  - "assets/node_modules"
  - "assets/Dockerfile"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "LICENSE"
  - ".github"
  - "test-results"

remote_theme: sylhare/Type-on-Strap